FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER root
WORKDIR /app
#COPY  ./InteractiveMapOfEnterprises.Server/wwwroot/geojson ./app/wwwroot/geojson
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["InteractiveMapOfEnterprises.Server/InteractiveMapOfEnterprises.Server.csproj", "InteractiveMapOfEnterprises.Server/"]
RUN dotnet restore "./InteractiveMapOfEnterprises.Server/./InteractiveMapOfEnterprises.Server.csproj"
WORKDIR /src
COPY ./InteractiveMapOfEnterprises.Server ./InteractiveMapOfEnterprises.Server
WORKDIR "/src/InteractiveMapOfEnterprises.Server"
RUN dotnet build "./InteractiveMapOfEnterprises.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./InteractiveMapOfEnterprises.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InteractiveMapOfEnterprises.Server.dll"]